apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: logger-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: logger-role
subjects:
- kind: ServiceAccount
  name: logger-service-account
  namespace: default
